#!/usr/bin/env bash
set -euo pipefail

# Commit and push badge changes
#
# Usage:
#   ./scripts/commit-badges.sh
#
# Environment variables (optional, for git identity):
#   GIT_AUTHOR_NAME
#   GIT_AUTHOR_EMAIL
#   GIT_COMMITTER_NAME
#   GIT_COMMITTER_EMAIL


# Check if repo is clean except for README.md and static/ badge files
DIRTY_FILES=$(git status --porcelain | awk '{print $2}')
NEEDS_PUSH=0
for FILE in $DIRTY_FILES; do
  # Allow README.md and anything under static/
  if [ "$FILE" = "README.md" ] || [[ "$FILE" == static/* ]]; then
    NEEDS_PUSH=1
    continue
  fi
  echo "Error: Repository has unstaged or uncommitted changes (excluding README.md and static/): $FILE"
  echo "Please commit or stash your changes before updating badges."
  exit 1
done

# Check if there are changes to commit
if [ "$NEEDS_PUSH" -ne 1 ]; then
  echo "No badge changes to commit"
  exit 0
fi

echo "Changes detected, committing..."

# Set git identity from environment variables if provided
# This works both in CI (with env vars set) and locally (using existing git config)
if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
  export GIT_AUTHOR_NAME
fi
if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
  export GIT_AUTHOR_EMAIL
fi
if [ -n "${GIT_COMMITTER_NAME:-}" ]; then
  export GIT_COMMITTER_NAME
fi
if [ -n "${GIT_COMMITTER_EMAIL:-}" ]; then
  export GIT_COMMITTER_EMAIL
fi

# Stage changes
git add README.md static/

# Create commit message
COMMIT_MSG="chore: update badges (automated)

This commit was automatically generated by the update-badges script."

# Commit and push
git commit -m "$COMMIT_MSG"
git push

echo "✓ Badges committed and pushed successfully"
