#!/usr/bin/env bash
set -euo pipefail

# Update badges and commit changes
#
# Usage:
#   ./scripts/update-badges.sh <test-status> <coverage>
#
# Arguments:
#   test-status: "passing" or "failing"
#   coverage: Coverage percentage (0-100)
#
# Environment variables (optional, for git identity):
#   GIT_AUTHOR_NAME
#   GIT_AUTHOR_EMAIL
#   GIT_COMMITTER_NAME
#   GIT_COMMITTER_EMAIL

# Check arguments
if [ $# -ne 2 ]; then
  echo "Usage: $0 <test-status> <coverage>"
  echo "  test-status: passing or failing"
  echo "  coverage: 0-100"
  exit 1
fi

TEST_STATUS="$1"
COVERAGE="$2"

# Validate test status
if [ "$TEST_STATUS" != "passing" ] && [ "$TEST_STATUS" != "failing" ]; then
  echo "Error: test-status must be 'passing' or 'failing'"
  exit 1
fi

# Validate coverage is a number
if ! [[ "$COVERAGE" =~ ^[0-9]+$ ]]; then
  echo "Error: coverage must be a number (0-100)"
  exit 1
fi

# Check if repo is clean except for README.md and static/ badge files
DIRTY_FILES=$(git status --porcelain | awk '{print $2}')

for FILE in $DIRTY_FILES; do
  # Allow README.md and anything under static/
  if [ "$FILE" != "README.md" ] && [[ "$FILE" != static/* ]]; then
    echo "Error: Repository has unstaged or uncommitted changes (excluding README.md and static/): $FILE"
    echo "Please commit or stash your changes before updating badges."
    exit 1
  fi
done


echo "Updating badges..."
echo "  Tests: $TEST_STATUS"
echo "  Coverage: $COVERAGE%"

# Update badges
cd gate && ./badges.ts --tests="$TEST_STATUS" --coverage="$COVERAGE"
cd ..

# Check if there are changes to commit
if [ -z "$(git status --porcelain)" ]; then
  echo "No badge changes to commit"
  exit 0
fi

echo "Changes detected, committing..."

# Set git identity from environment variables if provided
# This works both in CI (with env vars set) and locally (using existing git config)
if [ -n "${GIT_AUTHOR_NAME:-}" ]; then
  export GIT_AUTHOR_NAME
fi
if [ -n "${GIT_AUTHOR_EMAIL:-}" ]; then
  export GIT_AUTHOR_EMAIL
fi
if [ -n "${GIT_COMMITTER_NAME:-}" ]; then
  export GIT_COMMITTER_NAME
fi
if [ -n "${GIT_COMMITTER_EMAIL:-}" ]; then
  export GIT_COMMITTER_EMAIL
fi

# Stage changes
git add README.md static/

# Create commit message
COMMIT_MSG="chore: update badges (automated)

Tests: $TEST_STATUS
Coverage: $COVERAGE%

This commit was automatically generated by the update-badges script."

# Commit and push
git commit -m "$COMMIT_MSG"
git push

echo "✓ Badges updated, committed, and pushed successfully"
